### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by ocefpaf** [austinorr/mpl-template#10]
There is no license file and downstream packagers cannot use this software without one. The BSD-3-Clauses requires us to ship the upstream license with the package.

**Comment by austinorr** [comment]
Thanks for including my project! I’ll take care of this right away.

**Comment by austinorr** [comment]
License file added. Do I need to version bump and re-publish this to pypi in order to close this issue?

**Comment by ocefpaf** [comment]
> License file added. Do I need to version bump and re-publish this to pypi in order to close this issue?

Not for the conda-forge package. I can "hardcode" the license file there and we removed it when we have a new release.

**Comment by austinorr** [comment]
Ok, I'll bump and publish a little later then if it's not blocking you. Thanks again!
